# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kluctl < Formula
  desc "kluctl"
  homepage "https://kluctl.io/"
  version "2.16.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kluctl/kluctl/releases/download/v2.16.0/kluctl_v2.16.0_darwin_arm64.tar.gz"
      sha256 "9c84d413fe4476624438128769b907ac44e32de3dae7e419407e782dc0b353b5"

      def install
        bin.install "kluctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kluctl/kluctl/releases/download/v2.16.0/kluctl_v2.16.0_darwin_amd64.tar.gz"
      sha256 "5b32fc02324a4cb2aa831140a8d64b43b4cb68ee72a17ccb051db5f4313ca1ba"

      def install
        bin.install "kluctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kluctl/kluctl/releases/download/v2.16.0/kluctl_v2.16.0_linux_arm64.tar.gz"
      sha256 "0936c18ca6c14e7461ddaae30707c3366f77ead29066b2ba44e53aae5ac097e1"

      def install
        bin.install "kluctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kluctl/kluctl/releases/download/v2.16.0/kluctl_v2.16.0_linux_amd64.tar.gz"
      sha256 "86538a90885eb764777c2f3cd2b3f7dd3c2f70c1b2e7733c69bff4a558378afc"

      def install
        bin.install "kluctl"
      end
    end
  end

  test do
    system "#{bin}/kluctl version"

    bash_output = Utils.safe_popen_read(bin/"kluctl", "completion", "bash")
    (bash_completion/"kluctl").write bash_output

    zsh_output = Utils.safe_popen_read(bin/"kluctl", "completion", "zsh")
    (zsh_completion/"_kluctl").write zsh_output

    fish_output = Utils.safe_popen_read(bin/"kluctl", "completion", "fish")
    (fish_completion/"kluctl.fish").write fish_output
  end
end
