# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kluctl < Formula
  desc "kluctl"
  homepage "https://kluctl.io/"
  version "2.13.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kluctl/kluctl/releases/download/v2.13.1/kluctl_v2.13.1_darwin_arm64.tar.gz"
      sha256 "16877658a183472f254137325da198dbc22f1272f97fe2f05a796f2e9bca89ef"

      def install
        bin.install "kluctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kluctl/kluctl/releases/download/v2.13.1/kluctl_v2.13.1_darwin_amd64.tar.gz"
      sha256 "5c78ce7741d50675e8767d90e38cfa47e67c09ae90fa191ac7db2b8c83b09e96"

      def install
        bin.install "kluctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kluctl/kluctl/releases/download/v2.13.1/kluctl_v2.13.1_linux_amd64.tar.gz"
      sha256 "338a9a399e5c7249a2b416854d8a352e37ca38e85939caa0ee1c495b0486b7e1"

      def install
        bin.install "kluctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kluctl/kluctl/releases/download/v2.13.1/kluctl_v2.13.1_linux_arm64.tar.gz"
      sha256 "5e8642e61b27d07c1fb33682bed9b21e3a0b342d82dc496af32f89879abfe778"

      def install
        bin.install "kluctl"
      end
    end
  end

  test do
    system "#{bin}/kluctl version"

    bash_output = Utils.safe_popen_read(bin/"kluctl", "completion", "bash")
    (bash_completion/"kluctl").write bash_output

    zsh_output = Utils.safe_popen_read(bin/"kluctl", "completion", "zsh")
    (zsh_completion/"_kluctl").write zsh_output

    fish_output = Utils.safe_popen_read(bin/"kluctl", "completion", "fish")
    (fish_completion/"kluctl.fish").write fish_output
  end
end
